name: Trigger Scheduled Webhooks

on:
  schedule:
    # Run every 5 minutes (GitHub Actions minimum is 5 minutes)
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  trigger-webhooks:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        run: |
          curl -X POST \
            https://vxhmqlavlukdsfcqnllu.supabase.co/functions/v1/schedule-webhook-trigger \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json"
